pipeline {
    agent any
    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build('devops-demo-app', './app')
                }
            }
        }
        stage('Run Container') {
            steps {
                script {
                    docker.image('devops-demo-app').run('-p 5000:5000')
                }
            }
        }
    }
}
